Added docs for disabling top-level Virtual Host and configure Kourier
kserve/website pull request #187
Opened 2022-09-15 15:33 UTC by Suresh-Nakkeran

Signed-off-by: Suresh Nakkeran <suresh.n@ideas2it.com>

This PR is to add documentation for disabling top-level virtual service of Istio and also to set up Kourier as Networking Layer.

2022-09-27 18:02 UTC, alexagriffith commented on docs/modelserving/disable_toplevel_virutalhost/README.md
> +To disable top level virtual service add the flag `"disableIstioVirtualHost": true` under **ingress** config in inferenceservice configmap.
Can you add maybe a sentence or two explaining why this is important/when you want to do this/what the implications are?

2022-09-27 18:03 UTC, alexagriffith commented on docs/modelserving/disable_toplevel_virutalhost/README.md
> +To disable top level virtual service add the flag `"disableIstioVirtualHost": true` under **ingress** config in inferenceservice configmap.
I think that would help to tell a story for these docs for someone wanting to learn about this

2022-09-27 18:05 UTC, alexagriffith commented on docs/modelserving/kourier_networking/README.md
> +kourier network layer.
```suggestion
```

2022-09-27 18:08 UTC, alexagriffith commented on docs/modelserving/kourier_networking/README.md
> +# Deploy model without istio networking layer
```suggestion
# Deploy model with alternative networking layer
```

2022-09-27 18:09 UTC, alexagriffith commented on docs/modelserving/kourier_networking/README.md
> +## Port Forward kourier
```suggestion
## Port Forward Kourier
```

2022-09-27 18:11 UTC, alexagriffith commented on docs/modelserving/kourier_networking/README.md
> +## Restart the kserve
```suggestion
## Restart the KServe controller
```

2022-09-27 18:11 UTC, alexagriffith commented on docs/modelserving/kourier_networking/pmml-input.json
> +}
complains about no line EOF

2022-09-27 18:12 UTC, alexagriffith requested changes
small consistency changes/suggestions and add a little to intro :)

2022-10-03 17:14 UTC, alexagriffith commented on docs/modelserving/disable_toplevel_virutalhost/README.md
> +Kserve provides a option to disable istio top level virtual service.
```suggestion
Kserve provides an option to disable istio top level virtual service.
```

2022-10-22 14:13 UTC, yuzisun commented on mkdocs.yml
> +          - Networking Layer:
Let's move this to administration guide

2022-11-27 14:00 UTC, yuzisun commented
/lgtm
/approve

2022-11-27 14:01 UTC, merged