Changes to Homepage
kserve/website pull request #26
Opened 2021-09-21 08:36 UTC by js-ts

Site can be viewed at [site](https://cranky-lumiere-5df5c6.netlify.app/) 
Changes Made :
+ Added Favicon
+ Changed logo size
+ Added Top Banner
+ Added Banner
+ Added Points Section
+ Added Component Cards
+ Added Adopters Section
+ Changed controlplane.png
Will Add :
+ Blog
In the Next PR

2021-09-21 10:06 UTC, theofpa requested changes
Can we skip the files about building a docker image for mkdocs? It's better to keep the repo clean from the way of publishing it and focus on the content.

2021-09-21 21:07 UTC, yuzisun commented on overrides/home.html
> +            <a href="{{ 'getting_started/' | url }}" class="md-button md-button--primary">
/getting_started/get_started/gc

2021-09-21 21:16 UTC, yuzisun commented on overrides/home.html
> +          <input type="checkbox" checked disabled /><span class="task-list-indicator"></span>Provides <b>high scalability</b>, <b>density packing</b> and <b>intelligent routing</b> using <b>ModelMesh
nit: add period at the end.

2021-09-21 23:57 UTC, yuzisun approved these changes

2021-09-21 23:57 UTC, yuzisun commented
/lgtm
/approve

2021-09-21 23:58 UTC, yuzisun commented
Really awesome work! Thanks @js-ts !!

2021-09-22 07:56 UTC, js-ts commented
@theofpa Deleted All the docker and deployment files

Deleted .dockerignore
Deleted .gitlab-ci.yml
Deleted Dockerfile
Deleted amplify.yml
Deleted docker-compose.yml

2021-09-22 07:59 UTC, theofpa commented
Thank you @js-ts great stuff!

2021-09-22 08:00 UTC, theofpa commented
/lgtm
/appprove

2021-09-22 08:02 UTC, theofpa approved these changes

2021-09-22 12:44 UTC, merged