0.11 release blog
kserve/website pull request #310
Opened 2023-10-23 04:56 UTC by yuzisun

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

2023-10-24 17:47 UTC, rachitchauhan43 commented on docs/modelserving/v1beta1/llm/vllm/README.md
> +=== "Yaml"
YAML is not correctly rendering.

<img width="1084" alt="Screenshot 2023-10-24 at 10 10 46 AM" src="https://github.com/kserve/website/assets/8099140/3e45bcf5-1fd0-4950-892d-886a1da5c144">

2023-10-24 17:47 UTC, rachitchauhan43 commented on docs/modelserving/v1beta1/llm/vllm/README.md
> +The LLaMA model can be downloaded from [huggingface](https://huggingface.co/meta-llama/Llama-2-7b) and upload to your cloud storage.
```suggestion
The Llama-2-7b model can be downloaded from [huggingface](https://huggingface.co/meta-llama/Llama-2-7b) and upload to your cloud storage.
```

Just adding to explicitly call out that the benchmarking is for 7b model.

2023-10-27 16:15 UTC, rachitchauhan43 approved these changes
LGTM

2023-10-27 21:12 UTC, ckadner commented on docs/blog/articles/2023-10-08-KServe-0.11-release.md
> +### KServe Core Inference Enhancements
We are jumping from H1 (`#`) to H3 (`###`) level headings here.  Should we have `## KSreve Updates` above here like we have  `## ModelMesh Updates` below

2023-10-27 21:12 UTC, ckadner commented on docs/blog/articles/2023-10-08-KServe-0.11-release.md
> +We are excited to announce the release of KServe 0.11, in this release we introduced LLM runtimes, made enhancements to the KServe control plane, Python SDK Open Inference Protocol support and depend
most people would probably know it already, but should we spell out "Large Language Model (LLM)" at least once?

2023-10-27 21:13 UTC, ckadner commented on docs/blog/articles/2023-10-08-KServe-0.11-release.md
> +## :warning: What's Changed
this looks a little off, could we remove the :warning: emoji, or move it to the end

2023-10-30 20:36 UTC, ckadner requested changes
looks good, just one little nit I failed to notice earlier

2023-10-30 20:36 UTC, ckadner commented on docs/modelserving/v1beta1/llm/vllm/vllm.yaml
> +    minReplicas: 1
I think we need a newline at the end of file here, to allow concatenating manifest YAML files

2023-11-02 16:24 UTC, ckadner approved these changes
/lgtm

2023-11-02 16:25 UTC, ckadner commented
Looks good. Thanks Dan!

2023-11-02 16:25 UTC, merged